# Generated by Django 5.1.4 on 2024-12-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key_skills', models.TextField()),
                ('salary_from', models.FloatField(blank=True, null=True)),
                ('salary_to', models.FloatField(blank=True, null=True)),
                ('salary_currency', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=8)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Currency Rates',
                'db_table': 'currencies',
                'unique_together': {('date', 'currency_code')},
            },
        ),
    ]
