# Generated by Django 5.1.4 on 2024-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('avg_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Currency Statistics',
                'db_table': 'currency_statistics',
            },
        ),
    ]
