# Generated by Django 5.1.4 on 2024-12-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=8)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Currency Rates',
                'db_table': 'currencies',
                'unique_together': {('date', 'currency_code')},
            },
        ),
    ]
