# Generated by Django 5.1.4 on 2024-12-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_salarybyyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarybyyear',
            old_name='avg_rate',
            new_name='avg_salary',
        ),
    ]
