# Generated by Django 5.1.4 on 2024-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_avg_rate_salarybyyear_avg_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vacancy Count Statistics',
                'db_table': 'vacancies_count_by_year',
            },
        ),
    ]
