# Generated by Django 5.1.4 on 2024-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_vacanciescountbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('avg_salary', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'SalaryByCity Statistics',
                'db_table': 'salary_by_city_statistics',
            },
        ),
    ]
