# Generated by Django 5.1.4 on 2024-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_salarybycity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesCountByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'VacanciesCountByCity Statistics',
                'db_table': 'vacancies_count_by_city_statistics',
            },
        ),
    ]
