# Generated by Django 5.1.4 on 2024-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_vacanciescountbycity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'unique_together': {('year', 'name')},
            },
        ),
    ]
